# Generated by Django 3.2.7 on 2021-09-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20210927_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calc.calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calc.participant'),
        ),
    ]
