# Generated by Django 3.2.7 on 2021-09-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20210927_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendars',
            new_name='calendar',
        ),
    ]
