# Generated by Django 3.2.7 on 2021-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_rename_calendars_event_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('green', 'Green'), ('orange', 'Orange')], default='red', max_length=10),
        ),
    ]
