# Generated by Django 3.2.7 on 2021-09-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_event_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='calendar_name',
            new_name='name',
        ),
    ]
