# Generated by Django 3.2.7 on 2021-09-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_auto_20210927_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='events',
            new_name='event',
        ),
    ]
