# Generated by Django 3.2.7 on 2021-10-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20211006_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start',
        ),
    ]
