# Generated by Django 3.2.7 on 2021-10-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_auto_20211006_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('teal', 'Teal'), ('green', 'Green'), ('orange', 'Orange')], default='red', max_length=10),
        ),
    ]
